

user spider_robot
topic read  robot/spider/cmd/#
topic write robot/spider/cam/stream

user dashboard
topic write robot/spider/cmd/#
topic read  robot/spider/cam/stream
topic read  robot/spider/status 
user esp32
topic readwrite #