per_listener_settings true

# MQTT plain (local only)
listener 1883
allow_anonymous false
password_file /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/passwd
acl_file /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/acl.conf

# MQTT + TLS
listener 8883
cafile /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/certs/ca.crt
certfile /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/certs/server.crt
keyfile /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/certs/server.key
tls_version tlsv1.2
allow_anonymous false
password_file /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/passwd
acl_file /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/acl.conf

# WebSocket + TLS
listener 9001
protocol websockets
cafile /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/certs/ca.crt
certfile /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/certs/server.crt
keyfile /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/certs/server.key
tls_version tlsv1.2
allow_anonymous false
password_file /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/passwd
acl_file /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/acl.conf

# Plain WebSocket for local dev (no TLS)
listener 9002
protocol websockets
allow_anonymous false
password_file /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/passwd
acl_file /home/s4l1/Projet/Quadruped-robot-spider-UVO-0-name-to-be-changed-/mosquitto/acl.conf

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
